name: CI and deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: uv python install
      - run: uv sync --all-groups
      - run: uv run pre-commit run --all-files

  deploy:
    needs: pre-commit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'src/deployment/')
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Hugging Face
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/Noxem/ai_graph_estimation hf_repo
          cp -r src/deployment/* hf_repo/
          cd hf_repo
          git add .
          git commit -m "Sync deployment from GitHub" || echo "No changes to commit"
          git push origin main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
