name: CI and deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: uv python install
      - run: uv sync --group dev
      - run: uv run pre-commit run --all-files

  deploy:
    needs: pre-commit
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check if deployment files changed
        id: check-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^src/deployment/"; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi
      - name: Deploy to Hugging Face
        if: steps.check-changes.outputs.deploy == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git lfs install
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/Noxem/ai_graph_estimation hf_repo
          cp -r src/deployment/* hf_repo/
          cd hf_repo
          git lfs track "*.png" "*.jpg" "*.jpeg" "*.pkl"
          git add .
          git commit -m "Sync deployment from GitHub" || echo "No changes to commit"
          git push origin main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
