name: Sync Deployment to Hugging Face

on:
  push:
    paths:
      - 'deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face
        run: |
          cd deployment
          git remote set-url origin https://user:$HF_TOKEN@huggingface.co/spaces/Noxem/ai_graph_estimation
          git add .
          git commit -m "Sync deployment from GitHub" || echo "No changes to commit"
          git push origin main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
